version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/service/recorded-prdt
    overwrite: yes

permissions:
  - object: /
#    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user
