name: cicd_prdt

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

on: [workflow_dispatch]

env:
  PROJECT_NAME: nirey
  AWS_REGION: ap-northeast-2
  S3_BUCKET: nirey-cicd
  CODE_DEPLOY_APPLICATION_NAME: nirey-meomy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: recorded-prdt-01

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v4

    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

   # (3) Gradle build (Test 제외)
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test
      working-directory: ./${{ env.PROJECT_NAME }}    
